### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by Akityo** [harshil1712/n8n-nodes-pageres#1]
Error: Failed to launch the browser process! spawn /usr/local/lib/node_modules/n8n-nodes-pageres/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/n8n-nodes-pageres/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/n8n-nodes-pageres/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by harshil1712** [comment]
Hey @Akityo,

Were you able to solve it by following the instructions mentioned in the link you shared?

**Comment by M-IrtazaGhaffar** [comment]
Same problem with me either.
